name: BuildDeployCollectorLayer

on:
  workflow_dispatch

defaults:
  run:
    working-directory: .

jobs:
  BuildCollector:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the Collector repository
        uses: actions/checkout@v3
        with: 
          repository: open-telemetry/opentelemetry-lambda
          ref: refs/heads/main
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.0'
      - name: Build Collector
        working-directory: collector
        run: make
      - name: Install Collector - Remember the ARN
        working-directory: collector
        run: make publish-layer
